# Generated by Django 2.0.1 on 2018-01-11 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('synopsis', models.TextField(verbose_name='Synopsis')),
                ('pub_date', models.DateField(verbose_name='Date Published')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flix.Genre', verbose_name='Genre')),
            ],
            options={
                'verbose_name_plural': 'movies',
            },
        ),
    ]
