# Generated by Django 2.0.1 on 2018-01-11 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('synopsis', models.TextField(verbose_name='Synopsis')),
                ('pub_date', models.DateTimeField(verbose_name='Date Published')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flix.Category', verbose_name='Category')),
            ],
        ),
    ]
