# Generated by Django 2.0.1 on 2018-01-11 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flix', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-pub_date'], 'verbose_name_plural': 'movies'},
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='category',
            new_name='genre',
        ),
    ]
